[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)'

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 30
style = "bold red"

[aws]
symbol = 'â˜ï¸ '

[git_branch]
# symbol = "ğŸŒ± "
truncation_symbol = ""

[git_commit]
only_detached = false

[git_status]
modified = "*"

[ruby]
symbol = "ğŸ”º "

[time]
disabled = false

# [cmd_duration]
# disabled = true
